version: "3.1"

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chat
    restart: unless-stopped
    container_name: postgres_chat_db

volumes:
  data:
